references:
  docker_auth: &docker_auth
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_PASSWORD

  common_contexts: &common_contexts
    context:
      - docker-hub-creds
      - gemfury-api-access

  install_node_and_yarn: &install_node_and_yarn
    node/install:
      install-yarn: true

  restore_cache: &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

  install_build: &install_build
    run:
      name: Install & Build
      command: |
        gem install gemfury
        yarn
        yarn build

  yank_version_if_not_tagged: &yank_version_if_not_tagged
    run:
      name: Yank Version Unless It Is Tagged
      command: |
        DEPLOY_VERSION=$(npm -s run env echo '$npm_package_version')
        if [ $(git tag -l "$DEPLOY_VERSION") ]; then
          echo "Package version $DEPLOY_VERSION has already been tagged, will not redeploy"
          exit 1
        else
          fury yank babel-plugin-i18next-extract -v $DEPLOY_VERSION --api-token=$GEMFURY_API_TOKEN || echo "$DEPLOY_VERSION not on gemfury"
        fi

  deploy_version: &deploy_version
    run:
      name: Deploy Version
      command: |
        cd lib/
        DEPLOY_VERSION=$(npm -s run env echo '$npm_package_version')
        if [ "$CIRCLE_TAG" = "$DEPLOY_VERSION" ] || [ "$CIRCLE_TAG" = "" ]; then
          DEPLOY_FILE=$(npm pack | tail -n 1)
          fury push $DEPLOY_FILE --api-token=$GEMFURY_API_TOKEN
        else
          echo "Package version $DEPLOY_VERSION does not match git tag $CIRCLE_TAG"
          exit 1
        fi

version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  deploy_gemfury_develop:
    docker:
      - image: cimg/ruby:3.1.1
        <<: *docker_auth
    steps:
      - checkout
      - *install_node_and_yarn
      - *restore_cache
      - *install_build
      - *yank_version_if_not_tagged
      - *deploy_version
      - *save_cache
  deploy_gemfury_tagged:
    docker:
      - image: cimg/ruby:3.1.1
        <<: *docker_auth
    steps:
      - checkout
      - *install_node_and_yarn
      - *restore_cache
      - *install_build
      - *deploy_version
      - *save_cache

workflows:
  version: 2
  build:
    jobs:
      - deploy_gemfury_develop:
          <<: *common_contexts
          filters:
            branches:
              only: /develop|test-build/
      - deploy_gemfury_tagged:
          <<: *common_contexts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
